import { FounderBriefContent } from './entities/founder-brief.entity';
import { MarketSignal } from '../signals/entities/market-signal.entity';
import { SignalKind } from '../../common/enums';

/**
 * Deterministic calibration figures computed from the persisted signals — NOT
 * produced by the model. They let the reader gauge how much the brief rests on
 * stated facts vs model inference, and how confident the extraction was.
 */
export type SignalCalibration = {
  total: number;
  facts: number;
  hypotheses: number;
  avgConfidence: number;
  byCategory: Array<{ category: string; count: number }>;
};

export function computeCalibration(signals: MarketSignal[]): SignalCalibration {
  const facts = signals.filter((s) => s.kind === SignalKind.FACT).length;
  const hypotheses = signals.length - facts;
  const avg =
    signals.length === 0
      ? 0
      : signals.reduce((sum, s) => sum + s.confidence, 0) / signals.length;

  const counts = new Map<string, number>();
  for (const s of signals) {
    counts.set(s.category, (counts.get(s.category) ?? 0) + 1);
  }
  const byCategory = [...counts.entries()]
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count || a.category.localeCompare(b.category));

  return {
    total: signals.length,
    facts,
    hypotheses,
    avgConfidence: avg,
    byCategory,
  };
}

/**
 * Render a Founder Brief to Markdown. The sections deliberately mirror the
 * epistemic split of the content: findings (with evidence trail) → implications
 * → hypotheses → next experiment → uncertainty. Every finding lists the signals
 * it rests on, and every signal shows its own evidence source, so the reader
 * can trace any claim back to operator-supplied evidence.
 */
export function renderBriefMarkdown(
  title: string,
  content: FounderBriefContent,
  signals: MarketSignal[],
): string {
  const byId = new Map(signals.map((s) => [s.id, s]));
  const lines: string[] = [];

  lines.push(`# ${title}`, '');
  lines.push(
    '> Generated by Sytadel Growth OS from operator-supplied evidence.',
    '> Findings, hypotheses and recommendations are labeled separately.',
    '',
  );

  // Deterministic calibration block (computed, not model-authored).
  const cal = computeCalibration(signals);
  lines.push('## Signal base (calibration)', '');
  lines.push(
    `- signals: ${cal.total} (facts: ${cal.facts}, hypotheses: ${cal.hypotheses})`,
  );
  lines.push(`- average extraction confidence: ${cal.avgConfidence.toFixed(2)}`);
  if (cal.byCategory.length > 0) {
    const breakdown = cal.byCategory
      .map((c) => `${c.category}=${c.count}`)
      .join(', ');
    lines.push(`- by category: ${breakdown}`);
  }
  lines.push(
    '_These figures are computed from the signals, not written by the model._',
    '',
  );

  lines.push('## Findings', '');
  content.findings.forEach((f, i) => {
    lines.push(`${i + 1}. ${f.statement}`);
    for (const sid of f.signalIds) {
      const s = byId.get(sid);
      if (s) {
        lines.push(
          `   - evidence: [${s.category}/${s.kind}] ${s.statement} _(source: ${s.evidenceId})_`,
        );
      }
    }
  });
  lines.push('');

  section(lines, 'Implications for Sytadel', content.implicationsForSytadel);
  section(lines, 'Hypotheses to validate', content.hypothesesToValidate);

  lines.push('## Suggested next experiment', '', content.nextExperiment, '');

  section(
    lines,
    'Uncertainty & coverage limits',
    content.uncertaintyAndCoverage,
  );

  return lines.join('\n').trimEnd() + '\n';
}

function section(lines: string[], heading: string, items: string[]): void {
  lines.push(`## ${heading}`, '');
  if (items.length === 0) {
    lines.push('_None reported._', '');
    return;
  }
  for (const item of items) lines.push(`- ${item}`);
  lines.push('');
}
