import { FounderBriefContent } from './entities/founder-brief.entity';
import { MarketSignal } from '../signals/entities/market-signal.entity';

/**
 * Render a Founder Brief to Markdown. The sections deliberately mirror the
 * epistemic split of the content: findings (with evidence trail) → implications
 * → hypotheses → next experiment → uncertainty. Every finding lists the signals
 * it rests on, and every signal shows its own evidence source, so the reader
 * can trace any claim back to operator-supplied evidence.
 */
export function renderBriefMarkdown(
  title: string,
  content: FounderBriefContent,
  signals: MarketSignal[],
): string {
  const byId = new Map(signals.map((s) => [s.id, s]));
  const lines: string[] = [];

  lines.push(`# ${title}`, '');
  lines.push(
    '> Generated by Sytadel Growth OS from operator-supplied evidence.',
    '> Findings, hypotheses and recommendations are labeled separately.',
    '',
  );

  lines.push('## Findings', '');
  content.findings.forEach((f, i) => {
    lines.push(`${i + 1}. ${f.statement}`);
    for (const sid of f.signalIds) {
      const s = byId.get(sid);
      if (s) {
        lines.push(
          `   - evidence: [${s.category}/${s.kind}] ${s.statement} _(source: ${s.evidenceId})_`,
        );
      }
    }
  });
  lines.push('');

  section(lines, 'Implications for Sytadel', content.implicationsForSytadel);
  section(lines, 'Hypotheses to validate', content.hypothesesToValidate);

  lines.push('## Suggested next experiment', '', content.nextExperiment, '');

  section(
    lines,
    'Uncertainty & coverage limits',
    content.uncertaintyAndCoverage,
  );

  return lines.join('\n').trimEnd() + '\n';
}

function section(lines: string[], heading: string, items: string[]): void {
  lines.push(`## ${heading}`, '');
  if (items.length === 0) {
    lines.push('_None reported._', '');
    return;
  }
  for (const item of items) lines.push(`- ${item}`);
  lines.push('');
}
